#index:
#    path: /
#    controller: App\Controller\DefaultController::index
dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
currency:
    path: /admin/currency-exchange
    controller: App\Controller\Admin\CurrencyExchangeRateCrudController::index